Title:  Status
Subtitle:Status
Author:  Niels Thomas Haugård
Date:   Sun 25 Sep 2016 00:20:01 CEST
Version: b8fc69b-dirty
ShortTitle: D
Series:  SSI
SeriesIndex:
Tags: SSI
Cover: coverpage.pdf
CSS:  assets/CSS/nth2-number.css
html header: <link rel="stylesheet" href="assets/CSS/googlecode.css"> <script src="assets/CSS/highlight.min.js"></script> <script>hljs.initHighlightingOnLoad();</script>
Files: 
