Title:  Status
Subtitle:Status
Author:  Niels Thomas Haugård
Date:   Sat 24 Sep 2016 23:15:32 CEST
Version: b8fc69b-dirty
ShortTitle:  D
Series:  SSI
SeriesIndex:
Tags: SSI
Cover: coverpage.pdf
CSS:  assets/CSS/nth2-number.css
html header: <link rel="stylesheet" href="assets/CSS/googlecode.css"> <script src="assets/CSS/highlight.min.js"></script> <script>hljs.initHighlightingOnLoad();</script>
Files: status.md
